# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-22 13:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reward', '0002_awardletterrecipients'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AwardLetterRecipients',
        ),
    ]
