# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-22 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reward', '0003_delete_awardletterrecipients'),
    ]

    operations = [
        migrations.CreateModel(
            name='AwardLetterRecipients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
